name = "serverless"
compatibility_date = "2024-07-14"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cloudfare-api-bun-hono-drizzle-d1"
database_id = "5919508c-5800-4a70-b54d-bc89aa881fd8"

# [ai]
# binding = "AI"